export const AUTH_VERIFY_EMAIL = "AUTH_VERIFY_EMAIL";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const SET_ALERT_STATE = "SET_ALERT_STATE";
export const SET_USER_DASHBOARD_DATA = "SET_USER_DASHBOARD_DATA";